'''
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
import collections
class Solution:
    def findTheDifference5(self, s: str, t: str) -> str:
    #5: 数字与自身异或结果为0
        ans = 0
        for c in s: ans ^= ord(c)
        for c in t: ans ^= ord(c)

        return chr(ans)

    def findTheDifference4(self, s: str, t: str) -> str:
    #4: same as #2, but more simple
        return chr(sum(map(ord, t)) - sum(map(ord, s)))

    def findTheDifference3(self, s: str, t: str) -> str:
    #3: normal way
        list_t = list(t)
        for each in s:
            list_t.remove(each)

        return list_t[0]

    def findTheDifference2(self, s: str, t: str) -> str:
    #2: hash table
        hash_table = [0 for x in range(26)]

        for each in t:
            hash_table[ord(each) - ord('a')] += 1

        for each in s:
            hash_table[ord(each) - ord('a')] -= 1

        return chr(hash_table.index(1) + ord('a'))

    def findTheDifference1(self, s: str, t: str) -> str:
    #1: using Counter method
        return list(collections.Counter(t) - collections.Counter(s))[0]

s, t = 'aa', 'aca'
f = Solution()
print(f.findTheDifference1(s, t))
print(f.findTheDifference2(s, t))
print(f.findTheDifference3(s, t))
print(f.findTheDifference4(s, t))
print(f.findTheDifference5(s, t))